apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "locust.master" . }}
  labels:
    {{- include "locust.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "locust.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "locust.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "locust.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOCUST_HOST
              value: {{ .Values.master.target }}
            - name: LOCUST_WEB_PORT
              value: "{{ .Values.master.webPort }}"
            - name: LOCUST_MODE_MASTER
              value: "true"
          ports:
            - name: web-port
              containerPort: {{ .Values.master.webPort }}
              protocol: TCP
            - name: master-port
              containerPort: {{ .Values.master.commPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        locustRole: master
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
