apiVersion: v1
kind: Service
metadata:
  name: {{ template "locust.coordinator-service-web" . }}
  labels:
    {{- include "locust.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.locust.webPort }}
      protocol: TCP
  selector:
    {{- include "locust.selectorLabels" . | nindent 4 }}
